### PR TITLE
Updated color_picker_dialog and dynamic_color_theme to null-safety

### PR DESCRIPTION
**Pull request by Z-inator**
I updated color_picker_dialog and dynamic_color_theme to null-safety. I am quite new to open source development so I am not sure if I did it correctly. I didn't change anything inside of the other files but hopefully changing those two documents will help migrate the package to null-safety.

### CODE REVIEW

**Comment by DFreds** [comment]
Cool, thanks for doing this. I'm pretty behind on the latest changes to Flutter. Do you mind running the included sample app and verifying that it still works? Also, updating it if necessary.

**Comment by Z-inator** [comment]
I would absolutely love to, I may need some guidance though. I don't know how to properly fork and work on it. When I fork the repository I can't run anything in VS code because flutter isn't accessible(?). For example, all the imports are errors, but when I create a new flutter app and copy your code over, it isn't running as a fork and so I don't know how to create a pull request for it. I am pretty competent at working on my own code but I don't have a lot of experience working on others. I'll keep working on it and see what I can figure out. If you have any guidance, that would be great.

**Comment by DFreds** [comment]
Do you normally work with vs code and flutter? You need the Flutter extension and the Dart extension if you don't. Otherwise, just forking it should work fine as long as you have your Flutter environment setup. Unless something else is causing it to break in Flutter 2. I'll try messing with it sometime this week

**Comment by Z-inator** [comment]
Yes, I do, I have the flutter environment set up and I got the plugin and example working in a new app. Now when I try to create a pull request using my fork, GitHub tells me that our commit histories are completely different and so it won't let me merge it into yours. I have no idea what that means. I am still working on figuring it out though, I am trying to break into the software field for a long-term career so I am learning all I can.

**Comment by DFreds** [comment]
I see. You have a merge conflict. You should study a beginner course on git... But what I'm seeing on your fork is this: This branch is 3 commits ahead, 12 commits behind DFreds:master. 

If you just forked it, I'm not sure how you got 12 commits behind. Maybe just re-fork it via the UI in github and re-add your changes. There is a better way to do that, but it might be beyond your level at the moment.

**Comment by Z-inator** [comment]
I tried doing a rebase following online guides but it never finishes. I go through and resolve conflicts and then git add . those all back and run rebase --continue only for it to never finish. I am going to try and brute force it for now.

**Pull request closed without merging**
